import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import Image from "next/image";
import { Reactions } from "@prisma/client";

const reactions: { name: string; key: Reactions }[] = [
  { key: "RELATABLE", name: "✋ Relatable" },
  { key: "KEEP_GOING", name: "🔥 Keep going!" },
  { key: "GREAT_JOB", name: "👍 Great job!" },
];

const Home: NextPage = () => {
  const { data, isLoading } = trpc.useQuery(["post.all"]);

  return (
    <>
      <Head>
        <title>Peer Support</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='container mx-auto flex flex-col items-center justify-center min-h-screen p-4'>
        <h1 className='text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700'>
          Peer Support
        </h1>
        <div className='pt-6 flex justify-center items-center w-full'>
          {!isLoading && data?.posts.length === 0 && <p>No Posts Yet</p>}
          {data ? (
            <ul className='space-y-6'>
              {data.posts.map(post => {
                return (
                  <>
                    <li key={post.id + Math.random()} className='bg-gray-100 p-4 rounded-md '>
                      <div className='flex items-center gap-2'>
                        <Image
                          src={post.User.avatarUrl}
                          alt={post.User.name}
                          width='50'
                          height='50'
                        />
                        <div>
                          <h2>{post.User.name}</h2>
                          <span>{post.User.confidencePoint} confidence point</span>
                        </div>
                      </div>
                      <p className=''>{post.problem}</p>
                      <div className='flex gap-2'>
                        {reactions.map(reaction => (
                          <button
                            key={reaction.key}
                            className='px-2 py-1 text-sm  rounded-md bg-yellow-300'>
                            {reaction.name}
                          </button>
                        ))}
                      </div>
                    </li>
                    <li key={post.id + Math.random()} className='bg-gray-100 p-4 rounded-md '>
                      <div className='flex items-center gap-2'>
                        <Image
                          src={post.User.avatarUrl}
                          alt={post.User.name}
                          width='50'
                          height='50'
                        />
                        <div>
                          <h2>{post.User.name}</h2>
                          <span>{post.User.confidencePoint} confidence point</span>
                        </div>
                      </div>
                      <p className=''>{post.problem}</p>
                    </li>
                    <li key={post.id + Math.random()} className='bg-gray-100 p-4 rounded-md '>
                      <div className='flex items-center gap-2'>
                        <Image
                          src={post.User.avatarUrl}
                          alt={post.User.name}
                          width='50'
                          height='50'
                        />
                        <div>
                          <h2>{post.User.name}</h2>
                          <span>{post.User.confidencePoint} confidence point</span>
                        </div>
                      </div>
                      <p className=''>{post.problem}</p>
                    </li>
                    <li key={post.id + Math.random()} className='bg-gray-100 p-4 rounded-md '>
                      <div className='flex items-center gap-2'>
                        <Image
                          src={post.User.avatarUrl}
                          alt={post.User.name}
                          width='50'
                          height='50'
                        />
                        <div>
                          <h2>{post.User.name}</h2>
                          <span>{post.User.confidencePoint} confidence point</span>
                        </div>
                      </div>
                      <p className=''>{post.problem}</p>
                    </li>
                    <li key={post.id + Math.random()} className='bg-gray-100 p-4 rounded-md '>
                      <div className='flex items-center gap-2'>
                        <Image
                          src={post.User.avatarUrl}
                          alt={post.User.name}
                          width='50'
                          height='50'
                        />
                        <div>
                          <h2>{post.User.name}</h2>
                          <span>{post.User.confidencePoint} confidence point</span>
                        </div>
                      </div>
                      <p className=''>{post.problem}</p>
                    </li>
                  </>
                );
              })}
            </ul>
          ) : (
            <p>Loading..</p>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
