import { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { trpc } from "../../utils/trpc";

const PostDetail: NextPage = () => {
  const router = useRouter();
  const { id } = router.query;
  if (!id || typeof id !== "string") return null;

  const { data } = trpc.useQuery(["post.detail", { id }]);
  const { data: comments, isLoading } = trpc.useQuery(["comment.all"]);

  return (
    <>
      <Head>
        <title>Peer Support</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className=''>
        {data && (
          <div className='w-full'>
            <h1 className='text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700'>
              {data.title}
            </h1>
            <div>
              <Image src={data.User.avatarUrl} alt={data.User.name} width='50' height='50' />
              <span>{data.User.name}</span>
            </div>
          </div>
        )}
        <div className='w-full'>
          {comments && comments.length > 0 ? (
            <ul>
              {comments.map(comment => {
                return (
                  <li key={comment.id}>
                    <h3>{comment.User.name}</h3>
                    <p>{comment.content}</p>
                  </li>
                );
              })}
            </ul>
          ) : (
            <p>No Support yet!</p>
          )}
        </div>
      </main>
    </>
  );
};

export default PostDetail;
